name: datn_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.0.2
  http: ^1.1.0
  intl: ^0.18.1
  audioplayers: ^6.1.0
  file_selector: ^1.0.0
  flutter_sound: ^9.2.13
  permission_handler: ^11.0.0
  path_provider: ^2.1.1
  google_fonts: ^6.1.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_storage: ^12.0.0
  firebase_database: ^11.0.0
  cloud_firestore: ^5.0.0
  firebase_messaging: ^15.0.0
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.2
  provider: ^6.1.2
  firebase_app_check: ^0.3.2+6
  collection: ^1.17.1
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.0.0
  rxdart: ^0.27.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/avatar.jpg
    - assets/avatar2.png
    - assets/logo.png
